name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *" # 每6小时自动同步一次
  workflow_dispatch:
    # 这里定义了手动触发时弹出的表单
    inputs:
      upstream_repo:
        description: '上游仓库名 (例如: vercel/next.js)。留空则自动获取'
        required: false
        type: string
      upstream_branch:
        description: '上游分支名。留空则自动获取默认分支'
        required: false
        type: string
      target_branch:
        description: '你的目标分支名。留空则自动获取默认分支'
        required: false
        type: string

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    # 确保只在 fork 的仓库中运行
    if: ${{ github.event.repository.fork }}

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 自动生成，无需设置
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          # 神奇的语法：如果有手动输入就用输入的，否则自动从 GitHub 获取父级仓库信息
          upstream_sync_repo: ${{ inputs.upstream_repo || github.event.repository.parent.full_name }}
          upstream_sync_branch: ${{ inputs.upstream_branch || github.event.repository.parent.default_branch }}
          target_sync_branch: ${{ inputs.target_branch || github.event.repository.default_branch }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "同步失败，请手动检查代码冲突"
          exit 1
